pipeline:
  release:
    image: plugins/docker
    settings:
      repo: "${CI_REPO_OWNER##mu-}/${CI_REPO_NAME}"
      tags: "${CI_COMMIT_TAG##v}"
    secrets: [ docker_username, docker_password ]
    group: build
  build-and-push-jruby:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64
      repo: "${CI_REPO_OWNER##mu-}/${CI_REPO_NAME/ruby/jruby}"
      tags: "${CI_COMMIT_TAG##v}"
      dockerfile: Dockerfile.jruby
    secrets: [docker_username, docker_password]
    group: build
when:
  event: tag
  tag: v*
